CREATE TABLE IF NOT EXISTS USERS (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME VARCHAR(64) NOT NULL,
    LAST_NAME VARCHAR(64) NOT NULL,
    EMAIL VARCHAR(64) NOT NULL,
    PASSWORD VARCHAR(50) NOT NULL
);
CREATE TABLE IF NOT EXISTS PRINTED (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    TITLE VARCHAR(100) NOT NULL,
    AUTHOR VARCHAR(64) NOT NULL,
    YEAR_OF_PUBLICATION INT,
    PAGES INT,
    FEE_PRICE INT,
    IS_BORROWED BOOLEAN NOT NULL,
    FIELD VARCHAR2(64),
    GENRE VARCHAR2(64),
    COUNTRY VARCHAR2(64)
);