package com.biblior.biblior.entities;

public enum Genres {
    ACTION, ADVENTURE, ALTERNATE_HISTORY, ANTHOLOGY, CHICK_LIT, CHILDREN, CLASSIC,
    COMIC, COMING_OF_AGE, CRIME, DRAMA, FAIRYTALE, FANTASY, GRAPHIC_NOVEL, HISTORICAL,
    HORROR, MYSTERY, PARANORMAL_ROMANCE, PICTURE_BOOK, POETRY, POLITICAL_THRILLER, ROMANCE,
    SATIRE, SCIENCE_FICTION, SHORT_STORY, SUSPENSE, THRILLER, WESTERN, YOUNG_ADULT, ART, ARCHITECTURE, AUTOBIOGRAPHY,
    BIOGRAPHY, BUSINESS, ECONOMICS, CRAFT, HOBBIES, COOKBOOK, DIARY, DICTIONARY,
    ENCYCLOPEDIA, GUIDE, HEALTH, FITNESS, HISTORY, HOME_AND_GARDEN, HUMOR, JOURNAL, MATH, MEMOIR, PROGRAMMING,
    PHILOSOPHY, PRAYER, RELIGION, SPIRITUALITY, TEXTBOOK, TRUE_CRIME, REVIEW, SCIENCE, SELF_HELP, SPORTS_AND_LEISURE,
    TRAVEL
}
